"""
Lookup table for RP2350 Peripheral Register Bitfields.
Maps peripheral base addresses and register offsets to their bit-level metadata.
"""

# Dictionary structure:
# {
#   peripheral_base_hex: {
#     register_offset_hex: [
#       {"bits": (start, end), "name": "FIELD_NAME", "desc": "Description"},
#       ...
#     ]
#   }
# }

import json
import os

# Path to the autogenerated register map
REGS_JSON_PATH = os.path.join(os.path.dirname(__file__), "rp2350_regs.json")
CORE_REGS_PATH = os.path.join(os.path.dirname(__file__), "core_regs.json")

def load_metadata():
    combined_data = {
        "peripherals": {}, 
        "names": {},
        "arch_specific": {"ARM": {"peripherals": {}, "names": {}}, "RISCV": {"peripherals": {}, "names": {}}}
    }
    
    # Load primary SVD-based data (usually ARM-centric for RP2350)
    if os.path.exists(REGS_JSON_PATH):
        try:
            with open(REGS_JSON_PATH, 'r') as f:
                svd_data = json.load(f)
                combined_data["peripherals"].update(svd_data.get("peripherals", {}))
                combined_data["names"].update(svd_data.get("names", {}))
        except:
            pass
            
    # Load supplemental Core Peripheral data
    if os.path.exists(CORE_REGS_PATH):
        try:
            with open(CORE_REGS_PATH, 'r') as f:
                core_data = json.load(f)
                for arch in ["ARM", "RISCV"]:
                    if arch in core_data:
                        combined_data["arch_specific"][arch]["peripherals"] = core_data[arch].get("peripherals", {})
                        combined_data["arch_specific"][arch]["names"] = core_data[arch].get("names", {})
        except:
            pass

    # Sort bitfields by start bit for all maps
    def sort_periphs(p_map):
        for p_base in p_map:
            for r_off in p_map[p_base]:
                p_map[p_base][r_off].sort(key=lambda x: x["bits"][0])

    sort_periphs(combined_data["peripherals"])
    for arch in combined_data["arch_specific"]:
        sort_periphs(combined_data["arch_specific"][arch]["peripherals"])
            
    return combined_data

REGISTER_METADATA_FULL = load_metadata()
REGISTER_METADATA = REGISTER_METADATA_FULL.get("peripherals", {})
PERIPHERAL_NAMES = REGISTER_METADATA_FULL.get("names", {})
ARCH_METADATA = REGISTER_METADATA_FULL.get("arch_specific", {})

def get_bit_metadata(start_scan_addr, reg_offset_relative_to_scan, arch="ARM"):
    """
    Returns bit metadata list for a given register.
    Calculates absolute address and resolved matching peripheral + offset.
    """
    abs_addr = start_scan_addr + reg_offset_relative_to_scan
    
    # 1. Check Architecture Specific Overrides first (Core peripherals)
    arch_data = ARCH_METADATA.get(arch, {})
    arch_periphs = arch_data.get("peripherals", {})
    
    for base_hex, registers in arch_periphs.items():
        base_int = int(base_hex, 16)
        # Core peripherals often have very small blocks
        if base_int <= abs_addr < base_int + 0x100:
            actual_offset = abs_addr - base_int
            offset_hex = f"0x{actual_offset:08x}"
            return registers.get(offset_hex, [])

    # 2. Check Global Peripheral Map
    for base_hex, registers in REGISTER_METADATA.items():
        base_int = int(base_hex, 16)
        # RP2350 peripherals are often spaced by 0x4000
        if base_int <= abs_addr < base_int + 0x4000:
            actual_offset = abs_addr - base_int
            offset_hex = f"0x{actual_offset:08x}"
            return registers.get(offset_hex, [])
            
    return []

def get_peripheral_name(addr, arch="ARM"):
    """Returns the official peripheral name if address is within its block."""
    # 1. Check Architecture Specific first
    arch_data = ARCH_METADATA.get(arch, {})
    arch_names = arch_data.get("names", {})
    for base_hex, name in arch_names.items():
        base_int = int(base_hex, 16)
        if base_int <= addr < base_int + 0x100:
            return name

    # 2. Check Global names
    for base_hex, name in PERIPHERAL_NAMES.items():
        base_int = int(base_hex, 16)
        if 0x40000000 <= addr < 0x60000000 and base_int <= addr < base_int + 0x4000:
            return name
    return "Unknown"

def resolve_bit_info(bit_idx, metadata_list):
    """Finds which field a bit belongs to."""
    for item in metadata_list:
        start, end = item["bits"]
        if start <= bit_idx <= end:
            return item
    # User requested [UNDOCUMENTED] for missing data
    return {"bits": (bit_idx, bit_idx), "name": "[UNDOCUMENTED]", "desc": "No official definition found in SVD"}
